# Generated by Django 5.1.1 on 2024-10-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
